config/routes.rb
PersonalSite::Application.routes.draw do

	root to: 'home#index'

	match '/bio', to: 'home#bio'
	match '/html', to: 'home#html'
	match '/rails', to: 'home#rails'
	match '/javascript', to: 'home#javascript'
	match '/extra', to: 'home#extra'
	match '/contact', to: 'home#contact'
	match '/resume', to: 'home#resume'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end

	def bio

	end

	def html

	end

	def javascript

	end

	def rails

	end

	def contact

	end

	def extra

	end

	def resume

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<div class="footer">
	<p id="a">&#169 Kaljaa, Dew-Boms, L.L.C. <span>Contact: dew.boms.llc@gmail.com</span> | <%= link_to "Contract-Freelance Work", contact_path %></p>
	<p id="c">Site Designed and Built By Yours Truly, Ryan Flynn | Photo Credit: labutle.wordpress</p>
	<p id="c">Site Built with Ruby on Rails, JavaScript/Jquery, HTML5, and CSS3</p>
	<p id="b">All content within this document belongs to the respective copyright owners and/or Ryan Flynn of Dew-Boms, L.L.C.</p>
	<!--<p id="b">Content may not be reproduced or distributed without written consent of owner</p>-->
</div>

app/views/home/_header.html.erb
<div class= 'header' >
<!--
<img src="/assets/tree_branch_detailed2_green_crop.png" id="green_tree_header" />
<img src="/assets/tree_branch_detailed2_pink.png" id="pink_tree_header" />
<img src="/assets/tree_branch_detailed2.png" id="white_tree_header" />
-->
<h3 id="ryan_flynn_header"><%= link_to "Ryan <br> Flynn".html_safe, root_url %></h3>
<h4 id="ryan_flynn_qoute_header"> Web Developer & <br>Programmer</h4>

<div class= "toolbar">

	<ul>
		<li><%= link_to "Home".html_safe, root_url %></li>
		<li><%= link_to "Bio".html_safe, bio_path %></li>
		<li><%= link_to "Ruby/Rails".html_safe, rails_path %></li>
		<li><%= link_to "HTML5/CSS3".html_safe, html_path %></li>
		<li><%= link_to "Javscript/Query".html_safe, javascript_path %></li>
		<li><%= link_to "Extra".html_safe, extra_path %></li>
		<li><%= link_to "Contact".html_safe, contact_path %></li>
	</ul>

</div>
	
</div>

app/views/home/bio.html.erb
<div id= "homepage_background_2">

	<div class= "main_page">

		<%= render "header" %>

		<div class= "page_background">
		</div>

		<div class= "page">
			<h1 class="page_title" id="page_title_bio">Biography:</h1>
	
			<img src="/assets/bio_pic_1.jpg" alt="bio picture" id="bio_pic">

			<div id="bio_body">
				<h2>Hello There!</h2>
				<p>I&#39m not one to bloat but since I have built this site to impress you, I have to show off at least a little.</p>
				<p>I went to Virginia Tech doubling in Economics and HTM (Hospitality Tourism Management). I have always had a creative, entrepreneurial spirit so while there I started my own web venture, Kaljaa.  Through that, I have become very good at web development and programming.</p>
				<P>I'm not your stereotypical programmer. I started with a very heavy business background and then went into programming.  I went from trying to communicate business/web development ideas to programmers into programming myself. I now do both.  I understand the communication barrier between the programmer's world and the other end. This makes me a very good communicator.  I can take a person's idea, understand what they are trying to accomplish business wise, fill in the blanks, and translate that idea to the web.</p>
				<p>Progressive ideas, the competition, and science of successful business excite me and is one of my passions.  When it comes down to it, whatever it is, I will deliver.</p>
			</div>
	
		</div>


	</div>

	<%= render "footer" %>

</div>

app/views/home/contact.html.erb
<script>


</script>

<div id= "homepage_background_2">

	<div class= "main_page">

		<%= render "header" %>

		<div class= "page_background">
		</div>

		<div class= "page">

			<h1 class="page_title">Contact:</h1>
				<div class="contact">
					<p>Please feel free to send me a email or message me on LinkedIn anytime.  I am available for contract work so please contact me by the email or LinkedIn account below also. Thanks again!</p>
					<p> Email: dew.boms.llc@gmail.com</p>
					<p> LinkedIn: 
					<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
	<script type="IN/MemberProfile" data-id="http://www.linkedin.com/pub/ryan-flynn/24/79/436" data-format="hover" data-text="Ryan Flynn"></script>
					</p>
				</div>
		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/home/extra.html.erb
<div id= "homepage_background_2">

	<div class= "main_page">

		<%= render "header" %>

		<div class= "page_background">
		</div>

		<div class= "page">

			<div class= "extra">

				<h1>Extras:</h1>

				<p>Besides my three areas of concentration (Ruby/Ruby on Rails, Javascript/Jquery, HTML5/CSS3), here are some extra experiences, things I have done, and skills that I have.<p> 
				<p>These experiences and skills range from me working with them quite a bit to me briefly working with them.  I'll provide more details in each section.<p>
				<p>I will be more then happy to elaborate and talk about each of these topics in more detail.  Just send me a email and I will happily get back to you.</p>

			</div>

			<div class= "extra_box">

					<div id="tabs-0" class= "extra_tab">
					</div>
					<div id="tabs-1" class= "extra_tab">
						<h1>Kaljaa:</h1>
						<p>Kaljaa is a social site that I started with three other programmers about three years ago while still in school.  Kaljaa is a type of social network built with Ruby on Rails that is design specifically for the beer industry and culture.  Kaljaa is design to benefit each industry sector and fill their needs as a business, beer consumer, and media with emphasis on simplicity and effectiveness(<%= link_to "more info".html_safe, rails_path %>).</p>
<p>The site was temporarily launched in a very successful and well received clinical/beta trial. During that trial, Kaljaa had hundreds of users join that included people from all parts of the industry such as beer drinkers, breweries, beer distributors, restaurants, and critics.</p>
<p>Right now the site is being rebuilt and hopefully a new beta launch will be ready by the end of this June (fingers crossed).  Currently, due to graduations, new jobs, moves, and life in general, I am doing the rebuild mostly by myself and my programmers chime in when they can.</p>
<p>Thats about 3 years of craziness summed up as shortly as possible, :-).
					</div>
					<div id="tabs-2" class= "extra_tab">
						<h1>Resume:</h1>
						<p>This site is pretty much my resume but if there is a need for the paper version, I have links below.  One is on this site and the other is a downloadable pdf.</p>
						<p>Online Resume: <%= link_to "Click Here".html_safe, resume_path %></p>
						<p>PDF Download of Resume: <%= link_to "Click Here", "/Flynn_Ryan_Resume_Seattle_priv.pdf", :target => "_blank" %></p>
					</div>
					<div id="tabs-3" class= "extra_tab">
						<h1>Drupal:</h1>
						<p>I have done contract work for Drupal projects. Although my experience with Drupal is not extensive, I can accomplish most Drupal requests and projects without much trouble. I also have created a a personal demo site made in Drupal 7 (<a href="http://www.drupal.tislaa.com/" target="_blank">Drupal.Tislaa.com</a>).  Please ignore the written content on the demo site, it is very old/outdated and some of it is not correct. The site is just demo.</p>
					</div>
					<div id="tabs-4" class= "extra_tab">
						<h1>WordPress:</h1>
						<p>I have used and built some websites with WordPress.  I find WordPress very easy to use and most likely could accomplish most projects or requests for WordPress.  Like Drupal, I also have created a a personal demo site made in WordPress (<a href="http://www.wordpress.tislaa.com/" target="_blank">WordPress.Tislaa.com</a>).  Please ignore the written content on the demo site, it is very old/outdated and some of it is not correct.</p>
					</div>
					<div id="tabs-5" class= "extra_tab">
						<h1>PHP:</h1>
						<p>I first learned web development/ programming using PHP and a WAMP/LAMP.  I have not used it much as of late because I have been using Rails but it wouldn't take me that long to get back into the swing of things.  One of my first sites I built was in PHP.</p>  
						<p>On that site, I built a catalog, membership/profile, forum/blog, and interactive gallery all from scratch using PHP.  You can check it out here, oldsite (<a href="http://www.tislaa.com/" target="_blank">Tislaa.com</a>).</p>  <p>**Please ignore much of the written content on the site due to the fact it is old/outdated, some of it now incorrect, and written back in time of naiveness and mis-direction while learning to program, :-).</p>
					</div>
					<div id="tabs-6" class= "extra_tab">
						<h1>Design:</h1>
						<p>I pretty much do all my web designing and layouts myself.  The site you are currently on, Kaljaa, and any other site I have done has been designed and laid out by me.  I may not be as good as somebody who specializes in graphic-designs/layouts/web designs but I can hold my own.</p>
						<p>I understand the theories and ideas behind web design such as F-Layout, Z-Layout, grid base, visual hierarchy, color, usability, UX(User Experience), typography, and others.  I try my best to implement these ideas/theories and keep up to date with them.</p>
						<p>I have experience with and currently use Adobe products and other digital editors such as GIMP.  For the Adobe products, I mostly use Photoshop but I have briefly used their other programs such as Illustrator, InDesign, and Dreamweaver.</p>
					</div>
					<div id="tabs-7" class= "extra_tab">
						<h1 id="double_line_title">Project<br>Management:</h1>
<p>With Kaljaa, I have been leading and developing a very complex social network for the entire beer industry. I have been involved in all the steps in development. All the way from finding programmers, conceptual/graphic design, programming, and putting it to the web. </p>
<p>I have explored development methodologies such as Feature Driven Development (FDD), Scrum, and Agile to better my skills at project management.</p>
<p>I will say that the management of people, resources, and projects is one of my strongest attributes.  Other then the development of Kaljaa, I have single handily organized and ran complex, resource efficient, and very successful events involving groups ranging from 10 to a 115 people.</p>
<p>In terms of finding people, with YRCI, I have been involved in the recruitment and hiring of employees of varying positions for government agencies such as USDA, NSF, NRCS, and NFC.</p>
					</div>
					<div id="tabs-8" class= "extra_tab">
						<h1 id="double_line_title">Business<br>Management:</h1>
<p>My technical/web development background is based off a very strong business background. I went to Virginia Tech double majoring in Economics and Hospitality/Tourism Management. I'm also very passionate about the culture and science of business.</p>
<p>Ever since middle school, I have subscribe to and been interested in magazines such as Inc., Fast Company, The Economist, and Entrepreneur. I love the progressive ideas, the competition, and science of successful business.</p>
<p>Through my schooling, personal passion for business, and starting a personal web venture, I have great depth for business concepts and general know how.</p>
					</div>
					<div id="tabs-9" class= "extra_tab">
						<h1>Misc:</h1>
						<p>Couldn't think of anything really necessary to put here so here are some entertaining pictures instead.</p>
						<div id="pic1_click">
							<p>Click To See First Photo</p>
							<img id="pic1" src="/assets/lab.jpg" />
						</div>
						<div id="pic2_click">
							<p>Click To See Second Photo</p>
							<img id="pic2" src="/assets/pug.jpg" />
						</div>
						<div id="pic3_click">
							<p>Click To See Third Photo</p>
							<img id="pic3" src="/assets/monkey.jpg" />
						</div>
					</div>
					<ul>
						<li><a href="#tabs-0"></a></li>
						<li id= "bar1"><a href="#tabs-1">Kaljaa</a></li>
						<li id= "bar2"><a href="#tabs-2">Resume</a></li>
						<li id= "bar3"><a href="#tabs-3">Drupal</a></li>
						<li id= "bar4"><a href="#tabs-4">WordPress</a></li>
						<li id= "bar5"><a href="#tabs-5">PHP</a></li>
						<li id= "bar6"><a href="#tabs-6">Design</a></li>
						<li id= "bar7"><a href="#tabs-7">Project Management</a></li>
						<li id= "bar8"><a href="#tabs-8">Business Management</a></li>
						<li id= "bar9"><a href="#tabs-9">Misc</a></li>
					</ul>				
					<!--
					<div class= "color_links">
							<p id= "bar1"><a href="#tabs-1">Kaljaa</a></p>
							<p id= "bar2"><a href="#tabs-2">Resume</a></p>
							<p id= "bar3"><a href="#tabs-3">Drupal</a></p>
							<p id= "bar4"><a href="#tabs-4">WordPress</a></p>
							<p id= "bar5"><a href="#tabs-5">PHP</a></p>
							<p id= "bar6"><a href="#tabs-6">Design</a></p>
							<p id= "bar7"><a href="#tabs-7">Project Management</a></p>
							<p id= "bar8"><a href="#tabs-8">Business Management</a></p>
							<p id= "bar9"><a href="#tabs-9">Misc</a></p>
					</div>
					<div class= "extra_boxes">
						<p id="box1"><a href="#tabs-1">&nbspKaljaa</a></p>
						<p id="box2"><a href="#tabs-2">&nbspResume</a></p>
						<p id="box3"><a href="#tabs-3">&nbspDrupal</a></p>
						<p id="box4"><a href="#tabs-4">&nbspWordPress</a></p>
						<p id="box5"><a href="#tabs-5">&nbspPHP</a></p>
						<p id="box6"><a href="#tabs-6">&nbspDesign</a></p>
						<!-- this is a retarded way to do this, find better -->
						<!--<p id="box7"><a href="#tabs-7"> &nbspProject&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &nbspManagement</a></p>
						<p id="box8"><a href="#tabs-8"> &nbspBusiness&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &nbspManagement</a></p>
						<p id="box9"><a href="#tabs-9">&nbspMisc</a></p>
					</div>-->

					
					
			</div>
			

	
		</div>


	</div>

	<%= render "footer" %>

</div>

<script>
$(document).ready(function() {
   

	$('.extra_boxes p')
        .hover(function() {
            $(this).stop().animate({ top: -10 }, 'fast');
        }, function() {
            $(this).stop().animate({ top: 0 }, 'fast');
        });

		$(function() {
			$( ".extra_box" ).tabs();
		  });

		$("#pic1_click p").click(function(){
			$("#pic1").toggle();
			$("#pic2").hide();
			$("#pic3").hide();
		});
		$("#pic2_click p").click(function(){
			$("#pic2").toggle();
			$("#pic1").hide();
			$("#pic3").hide();
		});
		$("#pic3_click p").click(function(){
			$("#pic3").toggle();
			$("#pic2").hide();
			$("#pic1").hide();
		});
});

</script>

app/views/home/html.html.erb
<div id= "homepage_background_2">

	<div class= "main_page">

		<%= render "header" %>

		<div class= "page_background">
		</div>

		<div class= "page">

			<h1 id="javascript_title">HTML5/<br>CSS3:</h1>
			
			<div class="javascript_images">
				<div id="vimeo">
					<iframe src="http://player.vimeo.com/video/41444518" width="525px" height="295px" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen ></iframe>
				</div>

				<div class="css3">
					<p>CSS3</p>
				</div>

				<div id="html_5">
					<img src="/assets/HTML5_Logo_512.png" />
				</div>
			</div>
	
			<div class="javascript_body">
				<p>I am very comfortable with HTML and CSS.  I am also very comfortable with the new attributes, elements, storage, etc. of HTML 5 and the new features of CSS3 including browser capabilities.  I should have no problem completing any type of project dealing with HTML5/CSS3.  </p>
				<p>The only problem I could see me having is if the requirements are teetering on the “not possible” or it's something that the programming world has never heard of, :-).  Even with that, I doubt anything that is thrown at me will fall into that category so I should have no problem completing the project.</p>
				<P>I am also working on a App and mobile version for my web venture, Kaljaa, so I am familiar with the mobile aspects of web development with HTML5/CSS3.  I plan to have a mobile version of this site your currently on as soon as I find time.</p>
			</div>
	
		</div>


	</div>

	<%= render "footer" %>

</div>

app/views/home/index.html.erb
<div id= "homepage_background">	
			
	<div class= "homepage">
		<img src="/assets/tree_branch_detailed2_green_crop.png" id="green_tree_misc" />
		<img src="/assets/tree_branch_detailed2_pink.png" id="pink_tree_misc" />

		<img src="/assets/tree_branch_detailed2_green_crop.png" id="green_tree_jquery" />
		<img src="/assets/tree_branch_detailed2_pink.png" id="pink_tree_jquery" />

		<img src="/assets/tree_branch_detailed2_green_crop.png" id="green_tree_rails" />
		<img src="/assets/tree_branch_detailed2_pink.png" id="pink_tree_rails" />

		<img src="/assets/tree_branch_detailed2_green_crop.png" id="green_tree_html" />
		<img src="/assets/tree_branch_detailed2_pink.png" id="pink_tree_html" />
		
		<img src="/assets/tree_branch_detailed2_green_crop.png" id="green_tree" />
		<img src="/assets/tree_branch_detailed2_pink.png" id="pink_tree" />
		<img src="/assets/tree_branch_detailed2.png" id="white_tree" />

		<h1 id="ryan_flynn">Ryan <br> Flynn </h1>
		<h4 id="ryan_flynn_qoute"> Web Developer & <br> Programmer</h4>
		<div id="bio_link_home_page">
			<%= link_to "Bio", bio_path %>
		</div>
<div id="html_link_home_page">
		<%= link_to "HTML5/<br>CSS3".html_safe, html_path %>
</div>
<div id="rails_link_home_page">
		<%= link_to "Ruby/<br>Rails".html_safe, rails_path %>
</div>
<div id="javascript_link_home_page">
		<%= link_to "JavaScript/<br>jQuery".html_safe, javascript_path %>
</div>
<div id="misc_link_home_page">
		<%= link_to "Extra".html_safe, extra_path %>
</div>
<div id="contact_link_home_page">
		<%= link_to "Contact".html_safe, contact_path %>
</div>
		<h5 id="home_legal"> Site Designed and <br>Built By Yours Truly, <br>Ryan Flynn</h5>
		<p id="pic_credit">Photo Credit: labutle.wordpress</p>
		<h1 id= "js_test"> JAVASCRIPT</h1>


		<!--<div id="flip">Click to slide the panel down or up</div>
	<div id="panel"><img src="assets/rails.png" alt="some_text"></div>

		</div>-->
	</div>

</div>

<script> 
$(document).ready(function(){
  $("#flip").hover(function(){
    $("#panel").slideToggle("slow");
  });
	//trees fade
	
/*
	$("#rails_link_home_page").hover(function(){
		$("#pink_tree_rails").stop(true, true).fadeIn(700);
		$("#green_tree_rails").stop(true, true).fadeIn(700);
	},
	function(){
    	$("#pink_tree_rails").stop(true, true).fadeOut(2000);
		$("#green_tree_rails").stop(true, true).fadeOut(2000);
	});

	$(" #html_link_home_page").hover(function(){
		$("#pink_tree_html").stop(true, true).fadeIn(700);
		$("#green_tree_html").stop(true, true).fadeIn(700);
	},
	function(){
    	$("#pink_tree_html").stop(true, true).fadeOut(2000);
		$("#green_tree_html").stop(true, true).fadeOut(2000);
	});

	$("#javascript_link_home_page").hover(function(){
		$("#pink_tree_jquery").stop(true, true).fadeIn(700);
		$("#green_tree_jquery").stop(true, true).fadeIn(700);
	},
	function(){
    	$("#pink_tree_jquery").stop(true, true).fadeOut(2000);
		$("#green_tree_jquery").stop(true, true).fadeOut(2000);
	});
	
	$("#misc_link_home_page").hover(function(){
		$("#pink_tree_misc").stop(true, true).fadeIn(700);
		$("#green_tree_misc").stop(true, true).fadeIn(700);
	},
	function(){
    	$("#pink_tree_misc").stop(true, true).fadeOut(2000);
		$("#green_tree_misc").stop(true, true).fadeOut(2000);
	});
*/

	//buttons animation

	$('#bio_link_home_page')
        .hover(function() {
            $(this).stop().animate({ margin: '40px 0px 0px 600px', opacity: '1' }, 400);
        }, function() {
            $(this).stop().animate({ margin: '50px 0px 0px 600px', opacity: '.9'  }, 'fast');
        });

	$('#html_link_home_page')
        .hover(function() {
            $(this).stop().animate({ margin: '240px 0px 0px 725px', opacity: '1' }, 400);
        }, function() {
            $(this).stop().animate({ margin: '250px 0px 0px 725px', opacity: '.9'  }, 'fast');
        });

	$('#rails_link_home_page')
        .hover(function() {
            $(this).stop().animate({ margin: '340px 0px 0px 450px', opacity: '1' }, 400);
        }, function() {
            $(this).stop().animate({ margin: '350px 0px 0px 450px', opacity: '.9'  }, 'fast');
        });

	$('#javascript_link_home_page')
        .hover(function() {
            $(this).stop().animate({ margin: '515px 0px 0px 700px', opacity: '1' }, 400);
        }, function() {
            $(this).stop().animate({ margin: '525px 0px 0px 700px', opacity: '.9'  }, 'fast');
        });

	$('#misc_link_home_page')
        .hover(function() {
            $(this).stop().animate({ margin: '630px 0px 0px 390px', opacity: '1' }, 400);
        }, function() {
            $(this).stop().animate({ margin: '640px 0px 0px 390px', opacity: '.9'  }, 'fast');
        });

	$('#contact_link_home_page')
        .hover(function() {
            $(this).stop().animate({ margin: '740px 0px 0px 20px', opacity: '1' }, 400);
        }, function() {
            $(this).stop().animate({ margin: '750px 0px 0px 20px', opacity: '.9'  }, 'fast');
        });


	$('#bio_link_home_page, #html_link_home_page, #rails_link_home_page, #javascript_link_home_page, #misc_link_home_page')
        .hover(function() {
            $("#green_tree").stop().animate({ opacity: 1 }, 700);
			$("#pink_tree").stop().animate({ opacity: 1 }, 700);
        }, function() {
            $("#green_tree").stop().animate({ opacity: 0 }, 2000);
			$("#pink_tree").stop().animate({ opacity: 0 }, 2000);
        });

});

</script>

app/views/home/javascript.html.erb
<script> 
$(document).ready(function(){
	$(".jquery_animate").hover(function(){
		 $(this).animate({height: '210px', width:'210px', margin: '240px 0px 0px -10px'},"slow");
		$('.jquery_animate p').animate({fontSize: '50px'},"slow");
	/*}, function() {
            $(this).animate({height:'300px',opacity:'0.4'},"slow");
backgroundColor: "#aa0000", color: "#fff"
*/
	});
});
</script> 
<div id= "homepage_background_2">

	<div class= "main_page">

		<%= render "header" %>

		<div class= "page_background">
		</div>

		<div class= "page">

			<h1 id="javascript_title">Javascript/<br>jQuery:</h1>
			
			<div class="javascript_images">
				<div class="phone">
					<img src="/assets/phone.jpg" />
				</div>
				<img src="/assets/jquery.jpg" id="jquery"/>
				<div class="jquery_animate">
					<p>jQuery</p>
				</div>
				<div class="javascript_animate">
					<p>JavaScript</p>
				</div>
			</div>
	
			<div class="javascript_body">
				<p>Through my own web venture and other projects, I have had to do a good bit of JavaScript and jQuery. Anywhere from visual displays and animations to the not so exciting DOM/ Database(AJAX) interactions and manipulations.</p>
				<p>I would rate myself as a moderate Javascript/jQuery programmer in experience and ability. I am no expert in JavaScript/jQuery but at the same time I am far from a beginner.</p>
				<P>I could undertake and complete most projects concerning JavaScipt/jQuery but as one would expect, the more difficult and complex projects will take me longer than a expert programmer in Javascript/jQuery.</p>
				<p>I am also working on a App and mobile version for my web venture, Kaljaa, so I am familiar with the mobile aspects of web development with jQuery/JavaScript.  I plan to have a mobile version of this site your on currently as soon as I find time.</p>
			</div>


		</div>


	</div>

	<%= render "footer" %>

</div>

app/views/home/rails.html.erb
<div id= "homepage_background_2">

	<div class= "main_page_rails">

		<%= render "header" %>

		<div class= "page_background_rails">
		</div>

		<div class= "page_rails">
				<h1 class="page_title">Ruby/<br>Ruby on Rails:</h1>
			
			<div class="page_block_right" id="page_block_right">

				<img id="brewery_about" src="/assets/Breweryabout_small.jpg" />

				<img id="kaljaa_logo" src="/assets/kaljaa_logo_2.jpg" />

				<img id="kaljaa_login" src="/assets/kaljaauserlogin_small.jpg" />


				<img id="kaljaa_media" src="/assets/kaljaamedia_small.jpg" />


				<div class="tech">
					<p>Some of the features of the site<br> built in Rails:</p>
					<ul>
						<li>Blogging</li>
						<li>Login/Log Out/Validations</li>
						<li>News feed system</li>
						<li>Friend/Relationship system</li>
						<li>Rating system</li>
						<li>Trackers</li>
						<li>Information centrals</li>
						<li>Messaging system</li>
						<li>Calendar/Events system</li>
						<li>Settings</li>
						<li>Following and microposts</li>
						<li>Photos/Albums</li>
						<li>Reviews of products</li>
						<li>Marketing data</li>
						<li>Comments</li>
						<li>And many more</li>
						<li></li>
					</ul>
				</div>				

			</div>
	
			<div class="page_block_left" id="page_block_right">
				<p>Out of my three concentrations, I will say that Ruby on Rails is at the top in terms of skills and ability. My personal web venture, Kaljaa (<%= link_to "Learn More".html_safe, extra_path %>), is a type of social network designed for the entire beer industry. Kaljaa is a fairly large and complex site that I'm building in the Ruby on Rails framework.  I'm building the site with the intent (and the hope) to host thousands of users a day.</p>
				<p>After the initial build/beta release of Kaljaa and now my rebuild, which is nearing beta release, I have become very comfortable with Ruby on Rails.  I have also grown to really like Ruby on Rails. A little hesitant at first in my choice to use Rails, there was a little to much “magic” when programming with it for me.  That didn't last very long and now I'll say Rails is one of the best MVC you can use.</p>
				<p>I am not a expert in Ruby on Rails but I could likely complete most any project involving Ruby on Rails web development.</p>
				<p>***On the right, I have displayed screen shots from the original beta and I also listed some of the features and systems that I'm building into Kaljaa with Ruby on Rails. </p>
				<p>***I have a Github account with a public sample of the source code.  The source code contains what has been done/updated so far in the Kaljaa rebuild. Just keep in mine that the site is under construction so it may be a little messing since and also may not be as up to date as my main repository.  <a href="https://github.com/THEVT/kaljaa_public_sample" target="_blank">Kaljaa Github Sample.</a></p>
				<p>***I also have put up what has been completed so far for you to play around on (<a href="http://safe-forest-4101.herokuapp.com/" target="_blank">Kaljaa Dev</a>).  I disabled the creating a new profile but send me a email and I will give you a guest account.  Just remember that the site is still under heavy construction so no CSS styling has been done so its very ugly. Any CSS style that you do see are left overs from the first build/release and are there to keep my spirits up by not having a desolate looking screen when building.</p>
				<p>Also, many features are either not working/disabled, not built yet, kind of working, actually working, and one thing for sure, all of them need polish.  Also, the version you are on is most likely old and progress has been made since that version.  Bascially, have mercy, :-).</p>
			</div>
		</div>


	</div>

	<%= render "footer" %>

</div>

app/views/layouts/_header.html.erb
<h1>HELLLOOOOOOOOOOOO</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ryan Flynn</title>
	<LINK REL="SHORTCUT ICON" href="/assets/tab_pic.png">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
	<div id="main">
<%= yield %>
	</div>
</body>
</html>